### ISSUE TITLE
Bug with conversion from %m/%Y date format

### ISSUE THREAD

**Issue by hedjour** [hadley/lubridate#467] opened 2016-09-14 14:19 UTC
Hi
This code : 
`parse_date_time2(c("01/2013","09/2012"), c("%m,%Y") )` 
gives this results : 
`"2012-12-31 UTC" "2012-08-31 UTC"`
And not the expected result : 
`"2013-01-01 UTC" "2012-09-01 UTC"

Sorry for my short message English is not my native language.

**Comment by vspinu** [comment] 2016-09-14 14:42
Duplicate of #448.  Works fine with `v1.6.0`. What is your version?

```r
parse_date_time2(c("01/2013","09/2012"), c("%m,%Y") )
[1] "2013-01-01 UTC" "2012-09-01 UTC"
```

**Closed by vspinu** 2016-09-14 14:42 UTC

**Comment by hedjour** [comment] 2016-09-14 15:09
My version is the 1.5.6
