### ISSUE TITLE
problem printing data frames with duration objects 

### ISSUE THREAD

**Issue by Teebusch** [hadley/lubridate#512] opened 2017-01-27 17:38 UTC
I encountered this error when viewing data frames with duration objects in them. 

> Error in sprintf("%ds (~%s %ss)", x, x2, unit, "s)") : 
> invalid format '%d'; use format %f, %e, %g or %a for numeric objects

The durations I use are in seconds, but with 

- positions after the decimal point
- a large range of many orders of magnitude

I tried to isolate the problem. This is what I found:
 
```r
data.frame(d = c(dseconds(59.9))) # works
data.frame(d = c(dseconds(60.1))) # error

data.frame(d = c(dseconds(59.9), dseconds(60.1))) # works
data.frame(d = c(dseconds(1), dseconds(60.1))) # error
data.frame(d = c(dseconds(59.9), dseconds(60.0), dseconds(60.1))) #error

# same when using duration()
data.frame(d = c(duration(seconds = 59.9))) # works
data.frame(d = c(duration(seconds = 60.1))) # error
#...

# For minutes the problem occurs when there are 2 digits after the decimal point
data.frame(d = c(dminutes(59.9))) # works
data.frame(d = c(dminutes(60.1))) # works
data.frame(d = c(dminutes(59.91))) # error
data.frame(d = c(dminutes(60.11))) # error

data.frame(d = c(dminutes(59.1), dminutes(60.0), dminutes(60.1))) # works
data.frame(d = c(dminutes(59.11), dminutes(60.01), dminutes(60.11))) # error

# However, it works when there are two digits behind the comma for the last entry only
data.frame(d = c(dminutes(59.11), dminutes(60.1), dminutes(60.1))) # error
data.frame(d = c(dminutes(59.1), dminutes(60.11), dminutes(60.1))) # error
data.frame(d = c(dminutes(59.1), dminutes(60.1), dminutes(60.11))) # works
```

I'm using the latest version of R and RStudio, lubridate v. 1.6.0

**Comment by vspinu** [comment] 2017-01-29 16:30
Duplicate of #510, #493 and fixed by #465.

**Closed by vspinu** 2017-01-29 16:30 UTC
