### ISSUE TITLE
Is parse_date_time using more memory than as.POSIXct?

### ISSUE THREAD

**Issue by dracodoc** [hadley/lubridate#353] opened 2015-10-31 18:15 UTC
I'm trying to parse some date time column in a [10 million rows](https://nycopendata.socrata.com/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9) data.table. First I tried to create new column directly which failed after a long time:

	> nyc311[, create_date := parse_date_time('Created Date', tz = "America/New_York", "mdyT")]

	Garbage collection 67 = 25+5+37 (level 0) ... 
	898.9 Mbytes of cons cells used (81%)
	7547.8 Mbytes of vectors used (49%)
	Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
	Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?

At first I thought it could be `data.tabl` trying to update the huge object at the same time, so I wrote it separately instead of creating column in place. Turned out it is not the case. Instead `as.POSIXct` didn't have this problem. See the comparison below with the helper methods from package `pryr`:

`as.POSIXct` works without more memory usage

	> memory.size()
	[1] 9198.51
	> ptm = proc.time()
	> mem_change(as.POSIXct(nyc311$`Created Date`, format = "%m/%d/%Y %I:%M:%S %p"))
	-5.94 kB
	> proc.time() - ptm
	   user  system elapsed 
	 248.24    1.33  278.78 

`parse_date_time` didn't finish even with more memory available (I set memory limit to 16G):

	> memory.size()
	[1] 5716.69
	> ptm = proc.time()
	> mem_change(nyc311[, parse_date_time(`Created Date`, tz = "America/New_York", "%m/%d/%Y %I:%M:%S %p")])
	Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
	Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?
	> proc.time() - ptm
	   user  system elapsed 
	 256.79    2.10  303.72 

It doesn't help if I wrote separately without data.table syntax:

	> memory.size()
	[1] 8135.76
	> ptm = proc.time()
	> mem_change(parse_date_time(nyc311$`Created Date`, tz = "America/New_York", "%m/%d/%Y %I:%M:%S %p"))
	Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
	Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?
	> proc.time() - ptm
	   user  system elapsed 
	 259.58    2.48  279.07 

I also didn't see performance improvement I expected on `parse_date_time`. I knew `parse_date_time2` and `fast_strptime` probably will be much faster but I cannot use them since I need the `I` and `p` format to recognize AM/PM string.

**Comment by vspinu** [comment] 2015-10-31 18:31
You should see only marginal improvement over `as.POSIXct`  (2x or so) if parse_date_time doesn't drop into `fast_strptime`. I was never concerned with optimizing memory of non `fast_strptime` case. Nor I am particularly concerned right now because I want to move `I, AM/PM` and `b,B` formats to C parser ASAP.

My worry is with your infinite recursion. This should not happen. Could you provide a comprehensive sample of your date-times? Something that I can use to reproduce your problem. Like `ymd_hms(rep.int(sample, 1000))`.

**Comment by dracodoc** [comment] 2015-10-31 18:45
The infinite recursion only happens when the data is large enough. I tried on different size of samples, it only start to happen on 5 million rows (half size of the full data) sample.

You can get the data I used from [here](https://nycopendata.socrata.com/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9), choose `Export`, download csv. This is a 6G csv, took quite a while to download.

**Comment by vspinu** [comment] 2016-08-17 22:22
This should be fixed now. I have implemented C parser for PM/AM and English months. C parsing takes about 5 secs on this data for me.  

Most time consuming part is `force_tz` that is called at the end of the computation because of your `tz = "America/New_York"`.  And indeed, it consumes a non-trivial amount of memory. This I cannot solve at the moment. Consider sticking with `UTC` if it's an option.

As a side note, you should probably also stick with `mdy_hms(cdate)` or `parse_date_time2(..., 'mdyHMSp')` directly. Making `T` format work correctly with AM/PM is tricky on non C locales. You will also always end up into `strptime` with it instead of lubridate's C parser. I am considering deprecating "T" from the user level visibility.

**Closed by vspinu** 2016-08-17 22:22 UTC
Labels: question

**Comment by vspinu** [comment] 2016-08-19 13:14
>  Making T format work correctly with AM/PM is tricky on non C locales. You will also always end up into strptime with it instead of lubridate's C parser. I am considering deprecating "T" from the user level visibility.

Just for the record, the above is no longer true. `T` format drops into C parser whenever it makes sense and AM/PM are correctly handled irrespectively of the current locale.
