### ISSUE TITLE
problem with loadMethod for lubridate in Rscript

### ISSUE THREAD

**Issue by mccreigh** [hadley/lubridate#314] opened 2015-04-22 19:49 UTC
Compose the Rscript with file name `lubridateTest.Rsh`:

```{r}
#! /usr/bin/RScript
lubridate::round_date(Sys.time(),'minute')
```
Run it:
```{bash}
jamesmcc@chimayo:~> ./lubridateTest.Rsh 
Error in x - eseconds(1) : could not find function "loadMethod"
Calls: <Anonymous> ... as.POSIXct -> ceiling_date -> floor_date -> update -> -
recover called non-interactively; frames dumped, use debugger() to view
```
This works however:
```{r}
#! /usr/bin/RScript
library(lubridate)
lubridate::round_date(Sys.time(),'minute')
```
Run it:
```{r}
jamesmcc@chimayo:~> ./lubridateTest.Rsh 
Loading required package: methods
[1] "2015-04-22 13:25:00 MDT"
```

I have no idea why, but it just is this way. I'm curious to know however.
Thanks,
J

**Comment by vspinu** [comment] 2015-04-22 22:04
This applies to all S4 packages. The problem is that `methods` package is not attached from `Rscript`. This will work:

```
#! /usr/bin/Rscript
library(methods)
lubridate::round_date(Sys.time(),'minute')
```

I think there is a way around it, like explicitly calling `require(methods)` in `evalOnLoad`, but I am not sure we should bother with that. @hadley should know better what is the recommended way to deal with this issue.

**Comment by hadley** [comment] 2015-04-23 00:19
I think this might be fixed in 3.2

**Comment by vspinu** [comment] 2015-04-23 10:44
It's still there in today's devel but under a different form:

```
Error in dseconds(1) : could not find function "new"
Calls: <Anonymous> ... as.POSIXct -> ceiling_date -> floor_date -> update -> dseconds
In addition: Warning message:
no function found corresponding to methods exports from ‘lubridate’ for: ‘show’ 
Execution halted
```

**Comment by hadley** [comment] 2015-04-23 13:05
Are you importing the methods package and new etc?

**Comment by vspinu** [comment] 2015-04-23 15:13
> Are you importing the methods package and new etc?

Nope. `methods` is in Depends and no explicit imports for `new`, `show` etc are there. I guess that was it.

**Comment by vspinu** [comment] 2015-04-23 20:15
Ok. I have imported `new` and `show`. Now I am getting

```
Error in .setupMethodsTables(fdef, initialize = TRUE) : 
  trying to get slot "group" from an object of a basic class ("NULL") with no slots
Calls: <Anonymous> ... getMethodsForDispatch -> .getMethodsTable -> .setupMethodsTables
```

Importing the whole `methods` package results into:

```
Error in x - dseconds(1) : could not find function "loadMethod"
Calls: <Anonymous> ... as.POSIXct -> ceiling_date -> floor_date -> update -> -
```
Explicitly importing `loadMethods` doesn't help.

**Comment by hadley** [comment] 2015-04-23 21:49
Does `R CMD check` give anything helpful?

**Comment by vspinu** [comment] 2015-04-24 10:23
> Does R CMD check give anything helpful?

[Nope](https://travis-ci.org/hadley/lubridate).

**Comment by hadley** [comment] 2015-05-13 18:15
I now get

```
Rscript -e "lubridate::round_date(Sys.time(),'minute')"
[1] "2015-05-13 13:15:00 CDT"
```

**Comment by vspinu** [comment] 2015-05-13 19:03
> Rscript -e "lubridate::round_date(Sys.time(),'minute')"

Hm. It works for me as well. So it was magically fixed since then.

> I don't know how to make sure we've correctly imported every needed generic from methods though.

We can add this as a test to travis. So each time we rely on a method it's spotted.

**Comment by hadley** [comment] 2015-05-13 19:08
@vspinu it's not exactly magic - I made some commits to fix it ;)

**Comment by vspinu** [comment] 2015-05-13 21:07
Aha. I see. It's 8fa6ba347f080.

-----------------

I have added this one to the tests. You might want to have a lot at [it](https://github.com/hadley/lubridate/blob/master/tests/testthat/test-system.R).

The call executes fine on `test("path/to/lubridate")` but not on `check("path/to/lubridate")`.  I am deactivating it on Travis because of this. I also don't want to have a separate script for that because of the convenience of `devtools::test`. Any ideas?

**Closed by vspinu** 2015-05-13 21:07 UTC

**Comment by pchtsp** [comment] 2016-12-14 23:43
Not sure if I should open a new issue or use this one but:
This (original example) works:

    Rscript -e "lubridate::round_date(Sys.time(),'minute')"

But this doesn't:

    Rscript -e "lubridate::dhours(22)"

I get the following (sorry for the spanish):

    Error in .setupMethodsTables(fdef, initialize = TRUE) :
      tentativa de obtener un slot "group" de un objeto de una clase básica ("NULL") sin slots
    Calls: <Anonymous> ... getMethodsForDispatch -> .getMethodsTable -> .setupMethodsTables
    Ejecución interrumpida

I'm using lubridate as dependency in a package I'm building. I'm calling the package from a single R script that gets executed via Rscript.
I have tried adding `methods` and or `lubridate` as imports in the NAMESPACE of the package and still get the same error. I have finally had to add `library(methods)` to the R script that calls the package in order to make it work. But this doesn't appear to be a "nice" way of solving it.

Any advice?
