### ISSUE TITLE
Duration in summary of data.frame

### ISSUE THREAD

**Issue by mauricewendt** [hadley/lubridate#472] opened 2016-09-20 12:39 UTC
I want to summary a data-frame with summary(videos), where videos$DURATION is the video-length in seconds.

I get the following error if the data.frame exceeds a non-determinable size:

`Error in sprintf("%ds (~%s %ss)", x, x2, unit, "s)") : 
  invalid format '%d'; use format %f, %e, %g or %a for numeric objects`

The following Code reproduces the error, if you play around with the sample size:

set.seed(1)
videos <- data.frame(
  DURATION = lubridate::duration(
    sample(0:12345,10)                # sample 10 different durations (e.g. 1000 produces an error)
  )
)
summary(videos)

**Comment by vspinu** [comment] 2016-09-21 09:52
Strangly enough I cannot reproduce it with your code, but it seems to be the same issues as #465. Should be fixed once I pulled that PR.

**Closed** 2016-09-21 10:48 UTC
